Repository michaelbrusegard/chess-evolved, pull requests merged in 2025-04, with the labels that each got.

#51 [Feature] Add endgame presenter and view
  chessevolved_presenter/src/main/kotlin/io/github/chessevolved/presenters/EndGamePresenter.kt
  chessevolved_view/src/main/kotlin/io/github/chessevolved/views/EndGameView.kt
Labels: enhancement, ready for review

#39 State patterns scenes
  build.gradle
  chessevolved_model/src/main/kotlin/io/github/chessevolved/ExampleFile.kt
  chessevolved_presenter/src/main/kotlin/io/github/chessevolved/ChessEvolvedGame.kt
  chessevolved_presenter/src/main/kotlin/io/github/chessevolved/PresenterManager.kt
  chessevolved_presenter/src/main/kotlin/io/github/chessevolved/State.kt
  chessevolved_presenter/src/main/kotlin/io/github/chessevolved/presenters/GamePresenter.kt
  chessevolved_presenter/src/main/kotlin/io/github/chessevolved/presenters/JoinGamePresenter.kt
  chessevolved_presenter/src/main/kotlin/io/github/chessevolved/presenters/LobbyPresenter.kt
  chessevolved_presenter/src/main/kotlin/io/github/chessevolved/presenters/MenuPresenter.kt
  chessevolved_presenter/src/main/kotlin/io/github/chessevolved/presenters/SettingsPresenter.kt
  chessevolved_presenter/src/main/kotlin/io/github/chessevolved/presenters/StatePresenter.kt
  chessevolved_view/src/main/kotlin/io/github/chessevolved/views/AndroidView.kt
  chessevolved_view/src/main/kotlin/io/github/chessevolved/views/LobbyView.kt
  chessevolved_view/src/main/kotlin/io/github/chessevolved/views/MenuView.kt
  chessevolved_view/src/main/kotlin/io/github/chessevolved/views/SettingsView.kt
  lwjgl3/build.gradle
Labels: ready for review

#38 State/15 gamestate
  build.gradle
  chessevolved_model/build.gradle
  chessevolved_model/src/main/kotlin/io/github/chessevolved/components/AbilityComponent.kt
  chessevolved_model/src/main/kotlin/io/github/chessevolved/components/BoardSizeComponent.kt
  chessevolved_model/src/main/kotlin/io/github/chessevolved/components/GameState.kt
  chessevolved_model/src/main/kotlin/io/github/chessevolved/components/PieceTypeComponent.kt
  chessevolved_model/src/main/kotlin/io/github/chessevolved/components/PlayerColorComponent.kt
  chessevolved_model/src/main/kotlin/io/github/chessevolved/components/PositionComponent.kt
  chessevolved_model/src/main/kotlin/io/github/chessevolved/components/SerializableBoardSquare.kt
  chessevolved_model/src/main/kotlin/io/github/chessevolved/components/SerializablePiece.kt
  chessevolved_model/src/main/kotlin/io/github/chessevolved/components/WeatherEventComponent.kt
  chessevolved_model/src/main/kotlin/io/github/chessevolved/entities/BoardSquareFactory.kt
  chessevolved_model/src/main/kotlin/io/github/chessevolved/entities/ChessBoard.kt
  chessevolved_model/src/main/kotlin/io/github/chessevolved/entities/ChessPiece.kt
  chessevolved_model/src/main/kotlin/io/github/chessevolved/entities/PieceFactory.kt
  chessevolved_model/src/main/kotlin/io/github/chessevolved/singletons/GameStateSerializer.kt
  gradle.properties
Labels: enhancement, ready for review

#57 Feature/40 connect settings to supabase
  chessevolved_model/build.gradle
  chessevolved_model/src/main/kotlin/io/github/chessevolved/singletons/GameSettings.kt
  chessevolved_model/src/main/kotlin/io/github/chessevolved/singletons/Lobby.kt
  chessevolved_model/src/main/kotlin/io/github/chessevolved/singletons/supabase/SupabaseLobbyHandler.kt
  chessevolved_presenter/build.gradle
  chessevolved_presenter/src/main/kotlin/io/github/chessevolved/presenters/LobbyPresenter.kt
  chessevolved_presenter/src/main/kotlin/io/github/chessevolved/presenters/SettingsPresenter.kt
  chessevolved_shared/.gitignore
  chessevolved_shared/bin/main/io/github/chessevolved_shared/SettingsDTO.kt
  chessevolved_shared/build.gradle
  chessevolved_shared/src/main/kotlin/io/github/chessevolved_shared/SettingsDTO.kt
  chessevolved_view/build.gradle
  chessevolved_view/src/main/kotlin/io/github/chessevolved/views/SettingsView.kt
  settings.gradle
Labels: enhancement, ready for review

#60 Feature/59 add rematch functionality
  chessevolved_model/src/main/kotlin/io/github/chessevolved/singletons/Game.kt
  chessevolved_model/src/main/kotlin/io/github/chessevolved/singletons/Lobby.kt
  chessevolved_model/src/main/kotlin/io/github/chessevolved/singletons/supabase/SupabaseChannelManager.kt
  chessevolved_model/src/main/kotlin/io/github/chessevolved/singletons/supabase/SupabaseGameHandler.kt
  chessevolved_model/src/main/kotlin/io/github/chessevolved/singletons/supabase/SupabaseLobbyHandler.kt
  chessevolved_presenter/src/main/kotlin/io/github/chessevolved/Navigator.kt
  chessevolved_presenter/src/main/kotlin/io/github/chessevolved/presenters/EndGamePresenter.kt
  chessevolved_presenter/src/main/kotlin/io/github/chessevolved/presenters/GamePresenter.kt
  chessevolved_presenter/src/main/kotlin/io/github/chessevolved/presenters/LobbyPresenter.kt
  chessevolved_view/src/main/kotlin/io/github/chessevolved/views/EndGameView.kt
  chessevolved_view/src/main/kotlin/io/github/chessevolved/views/LobbyView.kt
  supabase/migrations/20250415195024_remote_schema.sql
Labels: enhancement, ready for review

#65 Add spritesheet for firetrail animation
  assets/sprites/firetrail/firetrail1.png
  assets/sprites/firetrail/firetrail2.png
  assets/sprites/firetrail/firetrail3.png
  assets/sprites/firetrail/firetrail4.png
Labels: enhancement, ready for review, graphics

#66 Feat/61 ability system
  .gitignore
  assets/ability/effects/explosion/explosion1.png
  assets/ability/effects/explosion/explosion2.png
  assets/ability/effects/explosion/explosion3.png
  assets/ability/effects/explosion/explosion4.png
  assets/ability/effects/explosion/explosion5.png
  assets/ability/effects/explosion/explosion6.png
  assets/ability/effects/shield/.gitkeep
  assets/ability/effects/shield/shield1.png
  assets/ability/effects/shield/shield2.png
  assets/ability/effects/shield/shield3.png
  assets/ability/effects/shield/shieldBreak1.png
  assets/ability/effects/shield/shieldBreak2.png
  assets/ability/effects/shield/shieldBreak3.png
  assets/ability/effects/shield/shieldBreak4.png
  assets/ability/effects/shield/shieldBreak5.png
  assets/ability/effects/shield/shieldBreak6.png
  chessevolved_model/src/main/kotlin/io/github/chessevolved/components/AbilityComponent.kt
  chessevolved_model/src/main/kotlin/io/github/chessevolved/components/AbilityTriggerComponent.kt
  chessevolved_model/src/main/kotlin/io/github/chessevolved/components/BlockedComponent.kt
  chessevolved_model/src/main/kotlin/io/github/chessevolved/components/CapturedComponent.kt
  chessevolved_model/src/main/kotlin/io/github/chessevolved/components/VisualEffectComponent.kt
  chessevolved_model/src/main/kotlin/io/github/chessevolved/entities/PieceFactory.kt
  chessevolved_model/src/main/kotlin/io/github/chessevolved/systems/AbilitySystem.kt
  chessevolved_model/src/main/kotlin/io/github/chessevolved/systems/CaptureSystem.kt
  chessevolved_model/src/main/kotlin/io/github/chessevolved/systems/MoveValidator.kt
  chessevolved_model/src/main/kotlin/io/github/chessevolved/systems/MovementSystem.kt
  chessevolved_model/src/main/kotlin/io/github/chessevolved/systems/VisualEffectSystem.kt
  chessevolved_presenter/src/main/kotlin/io/github/chessevolved/presenters/GamePresenter.kt
  chessevolved_shared/bin/main/io/github/chessevolved_shared/SettingsDTO.kt
Labels: enhancement, priority - high

#69 feat: :lipstick: add sprites for lightning, rain, and fow
  assets/ability/effects/firetrail/firetrail1.png
  assets/ability/effects/firetrail/firetrail2.png
  assets/ability/effects/firetrail/firetrail3.png
  assets/ability/effects/firetrail/firetrail4.png
  assets/ability/effects/fow/fow.png
  assets/ability/effects/lightningstorm/lightningstorm1.png
  assets/ability/effects/lightningstorm/lightningstorm2.png
  assets/ability/effects/lightningstorm/lightningstorm3.png
  assets/ability/effects/lightningstorm/lightningstorm4.png
  assets/ability/effects/lightningstorm/lightningstorm5.png
  assets/ability/effects/lightningstorm/lightningstorm6.png
  assets/ability/effects/rainstorm/rainstorm1.png
  assets/ability/effects/rainstorm/rainstorm2.png
  assets/ability/effects/rainstorm/rainstorm3.png
  assets/ability/effects/rainstorm/rainstorm4.png
  assets/ability/effects/rainstorm/rainstorm5.png
  assets/ability/effects/rainstorm/rainstorm6.png
Labels: ready for review, priority - medium, graphics

#73 Refactor/70 redesign redesign menu view
  android/AndroidManifest.xml
  assets/customUI/backgroundTile.png
  assets/customUI/buttonNormal.png
  assets/customUI/buttonPressed.png
  assets/customUI/checkboxChecked.png
  assets/customUI/checkboxUnchecked.png
  assets/customUI/chessEvolvedLogo.png
  assets/customUI/copySymbol.png
  assets/customUI/copySymbolPressed.png
  assets/customUI/labelPanel.png
  assets/customUI/pixeled.fnt
  assets/customUI/pixeled.png
  assets/customUI/textFieldPanel.png
  assets/customUI/textMarker.png
  assets/customUI/youloseLogo.png
  assets/customUI/youwinLogo.png
  chessevolved_model/src/main/kotlin/io/github/chessevolved/singletons/supabase/SupabaseClient.kt
  chessevolved_presenter/src/main/kotlin/io/github/chessevolved/presenters/EndGamePresenter.kt
  chessevolved_shared/build.gradle
  chessevolved_view/src/main/kotlin/io/github/chessevolved/SkinSetup.kt
  chessevolved_view/src/main/kotlin/io/github/chessevolved/ToastManager.kt
  chessevolved_view/src/main/kotlin/io/github/chessevolved/views/EndGameView.kt
  chessevolved_view/src/main/kotlin/io/github/chessevolved/views/JoinGameView.kt
  chessevolved_view/src/main/kotlin/io/github/chessevolved/views/LobbyView.kt
  chessevolved_view/src/main/kotlin/io/github/chessevolved/views/MenuView.kt
  chessevolved_view/src/main/kotlin/io/github/chessevolved/views/SettingsView.kt
Labels: enhancement, priority - medium, graphics

#75 feat: :sparkles: add fow handeling
  assets/ability/effects/fow/fow.png
  assets/board/fow.png
  chessevolved_model/src/main/kotlin/io/github/chessevolved/components/FowComponent.kt
  chessevolved_model/src/main/kotlin/io/github/chessevolved/entities/BoardSquareFactory.kt
  chessevolved_model/src/main/kotlin/io/github/chessevolved/systems/FowRenderingSystem.kt
  chessevolved_model/src/main/kotlin/io/github/chessevolved/systems/MovementSystem.kt
  chessevolved_presenter/src/main/kotlin/io/github/chessevolved/presenters/GamePresenter.kt
Labels: enhancement, ready for review, priority - high

#80 Feature/79 prevent invalid movement
  assets/abilities/cards/explosionCard.png
  assets/abilities/cards/new_movementCard.png
  assets/abilities/cards/swapCard.png
  assets/abilities/explosion-card-temp.png
  assets/abilities/explosion-card.png
  assets/abilities/shield-card.png
  assets/abilities/swap-card.png
  chessevolved_model/src/main/kotlin/io/github/chessevolved/entities/AbilityItemFactory.kt
  chessevolved_model/src/main/kotlin/io/github/chessevolved/entities/PieceFactory.kt
  chessevolved_model/src/main/kotlin/io/github/chessevolved/singletons/EcsEntityMapper.kt
  chessevolved_model/src/main/kotlin/io/github/chessevolved/singletons/Game.kt
  chessevolved_model/src/main/kotlin/io/github/chessevolved/singletons/GameSettings.kt
  chessevolved_model/src/main/kotlin/io/github/chessevolved/singletons/Lobby.kt
  chessevolved_model/src/main/kotlin/io/github/chessevolved/singletons/supabase/SupabaseGameHandler.kt
  chessevolved_model/src/main/kotlin/io/github/chessevolved/systems/InputSystem.kt
  chessevolved_model/src/main/kotlin/io/github/chessevolved/systems/SelectionEntityListener.kt
  chessevolved_presenter/src/main/kotlin/io/github/chessevolved/Navigator.kt
  chessevolved_presenter/src/main/kotlin/io/github/chessevolved/presenters/EndGamePresenter.kt
  chessevolved_presenter/src/main/kotlin/io/github/chessevolved/presenters/GamePresenter.kt
Labels: enhancement, ready for review, priority - high
