Repository michaelbrusegard/chess-evolved, pull requests merged in 2025-03, with the labels that each got.

#13 docs: add templates for issues and PRs
  .github/ISSUE_TEMPLATE/feature.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: documentation

#18 [presenter] Add basic LobbyPresenter
  chessevolved_presenter/src/main/kotlin/io/github/chessevolved/presenters/LobbyPresenter.kt
Labels: enhancement, ready for review

#16 [feature] add first iteration SettingsPresenter and GameSettings
  .github/PULL_REQUEST_TEMPLATE.md
  chessevolved_model/src/main/kotlin/io/github/chessevolved/singletons/GameSettings.kt
  chessevolved_presenter/src/main/kotlin/io/github/chessevolved/presenters/SettingsPresenter.kt
Labels: enhancement, ready for review

#14 [build] 4-change dependency between view and presenter
  android/build.gradle
  chessevolved_model/src/main/kotlin/io/github/chessevolved/components/SpriteComponent.kt
  chessevolved_presenter/build.gradle
  chessevolved_presenter/src/main/kotlin/io/github/chessevolved/ChessEvolvedGame.kt
  chessevolved_presenter/src/main/kotlin/io/github/chessevolved/presenters/GamePresenter.kt
  chessevolved_presenter/src/main/kotlin/io/github/chessevolved/presenters/IPresenter.kt
  chessevolved_view/build.gradle
  chessevolved_view/src/main/kotlin/io/github/chessevolved/views/AndroidView.kt
  chessevolved_view/src/main/kotlin/io/github/chessevolved/views/DesktopView.kt
  chessevolved_view/src/main/kotlin/io/github/chessevolved/views/IView.kt
  lwjgl3/build.gradle
  lwjgl3/src/main/kotlin/io/github/chessevolved/lwjgl3/Lwjgl3Launcher.kt
  settings.gradle
Labels: enhancement

#20 [bugfix] fix bugs and missing methods in presenters
  chessevolved_model/src/main/kotlin/io/github/chessevolved/singletons/GameSettings.kt
  chessevolved_presenter/src/main/kotlin/io/github/chessevolved/presenters/LobbyPresenter.kt
  chessevolved_presenter/src/main/kotlin/io/github/chessevolved/presenters/SettingsPresenter.kt
Labels: bug, ready for review

#35 [view] create settingsview
  chessevolved_presenter/src/main/kotlin/io/github/chessevolved/presenters/SettingsPresenter.kt
  chessevolved_view/src/main/kotlin/io/github/chessevolved/views/SettingsView.kt
Labels: enhancement, ready for review

#36 Feature/5 create supabase singleton
  .gitignore
  README.md
  chessevolved_model/build.gradle
  chessevolved_model/src/main/kotlin/io/github/chessevolved/singletons/supabase/SupabaseChannelManager.kt
  chessevolved_model/src/main/kotlin/io/github/chessevolved/singletons/supabase/SupabaseClient.kt
  chessevolved_model/src/main/kotlin/io/github/chessevolved/singletons/supabase/SupabaseGameHandler.kt
  chessevolved_model/src/main/kotlin/io/github/chessevolved/singletons/supabase/SupabaseLobbyHandler.kt
  chessevolved_presenter/src/main/kotlin/io/github/chessevolved/presenters/GamePresenter.kt
  gradle.properties
  supabase/.gitignore
  supabase/config.toml
  supabase/migrations/20250325162957_remote_schema.sql
  supabase/seed.sql
Labels: enhancement, ready for review
